# Site settings
title: Ph.D Sangkwon Kim
baseurl: "/sangkwon.github.io"
url: "https://ksk8863.github.io"
google_analytics: # Tracking ID, e.g. "UA-000000-01"

# Author
author:
  name: Sangkwon Kim
  desc: Applied Mathematics Researcher
  email: ksk8863@korea.ac.kr
  selfie: assets/img/image.jpg

# social
social:
  email: true
  behance:
  bitbucket:
  dribbble:
  facebook: 
  flickr:
  github: ksk8863
  google_plus:
  instagram: ksk8863
  keybase:
  linkedin: #https://www.linkedin.com/in/kssim/ 
  pinterest:
  reddit:
  soundcloud:
  stack_exchange:
  steam:
  tumblr:
  gitlab:
  twitter: ksk8863
  vimeo:
  wordpress:
  youtube: ksk8863
  default_txt: "Follow On"

# Build settings
markdown: kramdown

# Assets
sass:
  sass_dir: _sass
  style: compressed

# Gems
plugins:
  - jekyll-paginate

# Permalinks
permalink: /:year-:month-:day/:title
paginate_path: "/portfolio/page:num/"
paginate: 5
exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "*.gem"
  - "LICENSE"
  - "READE.md"
  - "screenshot.png"
